### ISSUE TITLE
.wav missing from .song file

### ISSUE THREAD

**Issue by rlbrinkman** [AkshayJames/arduino-midi-lights#1]
When I open the .song file at https://github.com/AkshayJames/arduino-midi-lights/blob/master/carol%20of%20the%20bells%20lights.song into Studio One it reports that the .wav file is missing.

Is the .wav file actually missing from the .song file, or am I doing something wrong?

**Comment by thetechmusician** [comment]
Thank you for reporting the issue. The .wav file was actually missing. I've uploaded the file and you can download it here: [www.dropbox.com/s/jj7p7djc437w2g5/Carol%20of%20the%20bells.wav?dl=1](url)

**Comment by rlbrinkman** [comment]
Thank you, I got the file - that fixed it!


________________________________

**Comment by GitJack101** [comment]
> Thank you for reporting the issue. The .wav file was actually missing. I've uploaded the file and you can download it here: [www.dropbox.com/s/jj7p7djc437w2g5/Carol%20of%20the%20bells.wav?dl=1](url)

Can you send link to .wav file again?
